apiVersion: apps/v1
kind: Deployment
metadata:
  name: trabalho-adrian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trabalho-adrian
  template:
    metadata:
      labels:
        app: trabalho-adrian
    spec:
      containers:
        - name: trabalho-adrian
          image: trabalho-adrian:latest
          imagePullPolicy: Never 
          ports:
          - containerPort: 3123
