# Usa a imagem oficial do NGINX como base.
FROM nginx:stable-alpine

# Remove o arquivo de configuração padrão do NGINX.
RUN rm /etc/nginx/conf.d/default.conf

# Copia nosso arquivo de configuração personalizado para dentro do contêiner.
COPY default.conf /etc/nginx/conf.d/