# Usa a imagem oficial do NGINX como base.
FROM nginx:stable-alpine

# Remove o arquivo padrão de configuração do NGINX.
RUN rm /etc/nginx/conf.d/default.conf

# Copia o arquivo de configuração para dentro do conteiner.
COPY default.conf /etc/nginx/conf.d/